name: Alerto
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: 4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  google_fonts: 6.1.0

flutter:
  uses-material-design: true
  assets:
  # Images
  - assets/images/alerto-logo.png
  - assets/images/alerto-bg.png
  - assets/images/alerto-logo.png

  # Icons
  - assets/icons/back-arrow-ic.png



flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/images/alerto-logo.png"
  remove_alpha_ios: true